* Loading faces
* Make them all white and black because the color does not defines the face, it's pixels
* Train the algorithm to detect faces 

In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


In [2]:
import os

In [3]:
os.listdir("C:/Users/admin/Pictures/")

['Camera Roll',
 'Capture.PNG',
 'desktop.ini',
 'me-riri.jpg',
 'Saved Pictures']

In [4]:
pwd = os.getcwd()
path = os.path.join(pwd,"C:/Users/admin/Pictures/photo1.PNG")

In [6]:
import cv2
img = cv2.imread(path, 0)
# 1 is the default flag It specifies to load a color image
# 0 It specifies to load an image in grayscale mode
# -1 It specifies to load an image as such including alpha channel

In [7]:
print(img)

[[138 134 127 ... 204 204 204]
 [139 139 133 ... 206 206 206]
 [140 140 136 ... 207 207 207]
 ...
 [ 59  61  64 ...  21  28  28]
 [ 59  59  61 ...  21  28  28]
 [ 59  59  59 ...  28  28  28]]


In [8]:
gray = cv2.imshow('test',img)
cv2.waitKey()

-1

In [9]:
#Convert to GrayScale
#grayscaled_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#cv2.imshow('test',grayscaled_img)

In [10]:
import cv2 
import numpy as np

In [19]:
img = cv2.imread("C:/Users/admin/Pictures/people.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [20]:
# face_cascade = cv2.CascadeClassifier('C:\\opencv\\build\\etc\\haarcascades\\haarcascade_frontalface_default.xml')
# eye_cascade = cv2.CascadeClassifier('C:\\opencv\\build\\etc\\haarcascades\\haarcascade_eye.xml')

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

faces = face_cascade.detectMultiScale(gray, 1.3, 5)
#faces = face_cascade.detectMultiScale(gray)

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

cv2.imshow('img',img)

k = cv2.waitKey(0)
if k == 27:         # wait for ESC key to exit
    cv2.destroyAllWindows()
elif k == ord('s'): # wait for 's' key to save and exit
    cv2.imwrite('messigray.png',img)
    cv2.destroyAllWindows()